import type { ProductInput } from "@/lib/types";

export const generatedContentJsonSchema = {
  name: "ecommerce_product_page_optimization",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      titles: { type: "array", items: { type: "string" } },
      coverCopies: { type: "array", items: { type: "string" } },
      sellingPoints: { type: "array", items: { type: "string" } },
      detailPageCopy: { type: "string" },
      xiaohongshuPosts: { type: "array", items: { type: "string" } },
      videoScripts: { type: "array", items: { type: "string" } },
      customerServiceReplies: { type: "array", items: { type: "string" } },
      negativeReviewReplies: { type: "array", items: { type: "string" } },
      differentiationAdvice: { type: "array", items: { type: "string" } },
      conversionAdvice: { type: "array", items: { type: "string" } },
      audienceTags: { type: "array", items: { type: "string" } },
      marketingHooks: { type: "array", items: { type: "string" } },
    },
    required: [
      "titles",
      "coverCopies",
      "sellingPoints",
      "detailPageCopy",
      "xiaohongshuPosts",
      "videoScripts",
      "customerServiceReplies",
      "negativeReviewReplies",
      "differentiationAdvice",
      "conversionAdvice",
      "audienceTags",
      "marketingHooks",
    ],
  },
} as const;

export function buildOptimizationPrompt(input: ProductInput) {
  return [
    "你是一名资深电商运营、商品详情页策划和广告投放优化专家。",
    "请根据用户输入，为商品页生成可执行的运营内容。",
    "必须只返回 JSON，不要返回 Markdown，不要添加解释文字，不要添加代码块。",
    "所有字段都必须存在，字段名必须完全一致。",
    "",
    "数量要求：",
    "- titles 必须正好 10 条。",
    "- coverCopies 必须正好 5 条。",
    "- sellingPoints 必须正好 6 条。",
    "- xiaohongshuPosts 必须正好 3 条。",
    "- videoScripts 必须正好 3 条。",
    "- customerServiceReplies 必须正好 8 条。",
    "- negativeReviewReplies 必须正好 5 条。",
    "- differentiationAdvice、conversionAdvice、audienceTags、marketingHooks 每项至少 5 条。",
    "",
    "内容要求：",
    "- 避免虚假承诺、绝对化广告用语和无法证明的功效描述。",
    "- 文案要贴合目标平台、目标人群、价格带和选择的风格。",
    "- 如果竞品信息为空，请基于常见同类商品做差异化建议。",
    "- 客服回复要自然、克制、可直接复制改写。",
    "- 差评回复要先共情，再解释，再给出解决动作。",
    "",
    "用户输入：",
    `商品名称：${input.productName}`,
    `商品类目：${input.category}`,
    `目标平台：${input.platform}`,
    `商品核心卖点：${input.sellingPointsInput}`,
    `目标人群：${input.targetAudience}`,
    `商品价格区间：${input.priceRange || "未提供"}`,
    `竞品链接或竞品描述：${input.competitorInfo || "未提供"}`,
    `用户痛点：${input.painPoints || "未提供"}`,
    `风格选择：${input.tone}`,
    `输出语言：${input.language}`,
  ].join("\n");
}
