import { createHash } from "node:crypto";

import type { Stage15SourceNativeEvaluationMaterials } from "./stage15-source-native-evaluation";

type Workbench = { html: string; htmlHash: string; storageKey: string };

function sha256(value: string): string { return createHash("sha256").update(value, "utf8").digest("hex"); }
function escapeHtml(value: unknown): string { return String(value ?? "").replace(/&/gu, "&amp;").replace(/</gu, "&lt;").replace(/>/gu, "&gt;").replace(/"/gu, "&quot;").replace(/'/gu, "&#39;"); }
function embedded(value: unknown): string { return JSON.stringify(value).replace(/</gu, "\\u003c").replace(/>/gu, "\\u003e").replace(/&/gu, "\\u0026"); }

function render(input: { role: "screening_operator" | "outcome_assessor_a" | "outcome_assessor_b"; packet: { packetHash: string; cards: Array<Record<string, unknown>> }; template: Record<string, unknown>; outcome: boolean }): Workbench {
  const storageKey = `stage15-source-native:${input.role}:${input.packet.packetHash}`;
  const fields = input.outcome ? ["productUnderstood", "evidenceSufficient", "worthFurtherInvestigation", "confidence"] : ["productUnderstood", "evidenceSufficient", "obviousConcern", "investigateNext10Minutes", "confidence"];
  const rich = (card: Record<string, unknown>) => { if (!input.outcome) return ""; const display = card.display as Record<string, unknown>; const specs = card.specifications as Record<string, unknown>; const reviews = (card.reviewSignals as Array<Record<string, unknown>>).map((review) => `${escapeHtml(review.sentiment)} ${escapeHtml(review.rating)} ${escapeHtml(review.reviewedAt)} ${escapeHtml(review.signal)}`).join(" | "); const quality = (card.qualitySignals as Array<Record<string, unknown>>).map((signal) => `${escapeHtml(signal.sentiment)} ${escapeHtml(signal.signal)}`).join(" | "); return `<section class="rich-outcome-evidence"><p>brand: ${escapeHtml(display.brand)}; model: ${escapeHtml(display.model)}; variant: ${escapeHtml(display.variant)}</p><p>dimensions: ${escapeHtml(specs.dimensions)}; weight: ${escapeHtml(specs.weight)}; materials: ${escapeHtml((specs.materials as string[]).join(", "))}; features: ${escapeHtml((specs.features as string[]).join(", "))}</p><p>review signals: ${reviews}</p><p>quality signals: ${quality}</p></section>`; };
  const cards = input.packet.cards.map((card) => `<article data-item="${escapeHtml(card.evaluationItemId)}"><h2>${escapeHtml(card.evaluationItemId)} · ${escapeHtml(card.title)}</h2><p>${escapeHtml(card.price)} ${escapeHtml(card.currency)} · ${escapeHtml(card.rating)} · ${escapeHtml(card.reviewCount)}</p><p>${escapeHtml((card.missingReasons as string[]).join(", "))}</p><div data-assets="${escapeHtml((card.imageAssetRefs as string[]).join(","))}"></div>${rich(card)}${fields.map((field) => `<label>${escapeHtml(field)}<select data-field="${escapeHtml(field)}"><option value=""></option>${(field === "confidence" ? ["high", "medium", "low"] : field === "worthFurtherInvestigation" ? ["yes", "no", "insufficient_evidence"] : field === "evidenceSufficient" && input.outcome ? ["yes", "no"] : ["yes", "no", "uncertain"]).map((value) => `<option value="${value}">${value}</option>`).join("")}</select></label>`).join("")}<label>elapsedSeconds<input type="number" min="1" data-field="elapsedSeconds"></label>${input.outcome ? `<fieldset><legend>dominantSignals</legend>${["market_validation", "listing_maturity", "buyer_reviews", "product_fit", "risk", "other"].map((signal) => `<label><input type="checkbox" data-field="dominantSignals" value="${signal}">${signal}</label>`).join("")}</fieldset><label>reason<textarea data-field="reason"></textarea></label>` : `<label>note<textarea data-field="note"></textarea></label>`}</article>`).join("\n");
  const complete = input.outcome ? "return a.productUnderstood&&a.evidenceSufficient&&a.worthFurtherInvestigation&&a.confidence&&a.elapsedSeconds>0&&a.dominantSignals.length>0&&a.reason.trim().length>0&&a.reason.length<=500" : "return a.productUnderstood&&a.evidenceSufficient&&a.obviousConcern&&a.investigateNext10Minutes&&a.confidence&&a.elapsedSeconds>0&&a.note.trim().length>0&&a.note.length<=500";
  const attestation = input.outcome ? `<fieldset><legend>roleIndependenceAttested</legend><label><input type="checkbox" name="attested" value="true">true</label></fieldset>` : "";
  const completionGate = input.outcome ? "||attestedValue!==true" : "";
  const resultAttestation = input.outcome ? ",roleIndependenceAttested:attestedValue" : "";
  const answerSeed = input.outcome ? "{evaluationItemId:c.dataset.item,dominantSignals:[]}" : "{evaluationItemId:c.dataset.item}";
  const collectFields = input.outcome ? "for(const n of c.querySelectorAll('[data-field]')){if(n.type==='checkbox'){if(n.checked)a.dominantSignals.push(n.value)}else a[n.dataset.field]=n.value}" : "for(const n of c.querySelectorAll('[data-field]'))a[n.dataset.field]=n.value";
  const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>Stage 1.5 evaluation</title></head><body>${attestation}<main>${cards}</main><button id="save">save local draft</button><button id="export">export JSON</button><script>const packet=${embedded(input.packet)};const seed=${embedded(input.template)};const storageKey=${embedded(storageKey)};function canonical(v){if(v===null||typeof v==='string'||typeof v==='boolean')return JSON.stringify(v);if(typeof v==='number')return JSON.stringify(Object.is(v,-0)?0:v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}async function digest(v){const bytes=new TextEncoder().encode(canonical(v));const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}function collectCard(c){const a=${answerSeed};${collectFields}a.elapsedSeconds=Number(a.elapsedSeconds);return a}function collect(){return [...document.querySelectorAll('[data-item]')].map(collectCard)}function complete(a){${complete}}function save(){localStorage.setItem(storageKey,JSON.stringify({answers:collect()}))}document.getElementById('save').onclick=save;document.getElementById('export').onclick=async()=>{const answers=collect();const attestedValue=document.querySelector('[name="attested"]')?.checked===true;if(answers.length!==20||!answers.every(complete)${completionGate}){alert('complete all 20 items');return}const result={...seed,status:'completed',completedAt:new Date().toISOString(),answers:collect()${resultAttestation}};result.resultHash=await digest(result);const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=seed.role+'-result.json';link.click();URL.revokeObjectURL(link.href)}</script></body></html>`;
  return { html, htmlHash: sha256(html), storageKey };
}

export function generateStage15SourceNativeWorkbenches(materials: Stage15SourceNativeEvaluationMaterials): { operator: Workbench; assessorA: Workbench; assessorB: Workbench } {
  return {
    operator: render({ role: "screening_operator", packet: materials.operator.packet, template: materials.operator.template, outcome: false }),
    assessorA: render({ role: "outcome_assessor_a", packet: materials.outcome.packet, template: materials.outcome.assessorA.template, outcome: true }),
    assessorB: render({ role: "outcome_assessor_b", packet: materials.outcome.packet, template: materials.outcome.assessorB.template, outcome: true }),
  };
}
