import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { requireAuthenticated } from "@/lib/server/demoGuard";
import { readBrowserEvidenceTaskAsin } from "@/lib/server/browserEvidence";
import { browserEvidenceSubjectKey, collectBrowserEvidencePreview } from "@/lib/server/browserEvidenceCollect";
import { buildAmazonFactEnrichmentPreview } from "@/lib/server/amazonFactEnrichment/service";
import type { AmazonFactEnrichmentPreviewV1 } from "@/lib/server/amazonFactEnrichment/contract";
export const runtime="nodejs";
type Entry={id:string;preview:AmazonFactEnrichmentPreviewV1;subjectKey:string}; const store=new Map<string,Entry>();
function prune(){const now=Date.now();for(const [k,v] of store)if(v.preview.expiresAt<=now)store.delete(k);}
function response(body:unknown,status=200){return NextResponse.json(body,{status});}
export async function GET(req:NextRequest,ctx:{params:Promise<{id?:string}>}){const auth=requireAuthenticated(req);if(!auth.ok)return response({ok:false,error:{code:auth.code,message:auth.message}},auth.status);const {id}=await ctx.params; if(!id)return response({ok:false,error:{code:"invalid_task_id",message:"缺少有效 task id。"}},400); prune(); const asin=await readBrowserEvidenceTaskAsin(auth.context,id); if(!asin)return response({ok:false,error:{code:"task_asin_unbound",message:"当前任务缺少权威 Amazon ASIN。"}},400); const found=[...store.values()].find(e=>e.subjectKey===browserEvidenceSubjectKey(auth.context)&&e.preview.taskId===id&&e.preview.asin===asin); return response({ok:true,data:{status:found?"pending":"empty",asin,preview:found?.preview??null}});}
export async function POST(req:NextRequest,ctx:{params:Promise<{id?:string}>}){const auth=requireAuthenticated(req);if(!auth.ok)return response({ok:false,error:{code:auth.code,message:auth.message}},auth.status);const {id}=await ctx.params;if(!id)return response({ok:false,error:{code:"invalid_task_id",message:"缺少有效 task id。"}},400);const asin=await readBrowserEvidenceTaskAsin(auth.context,id);if(!asin)return response({ok:false,error:{code:"task_asin_unbound",message:"当前任务缺少权威 Amazon ASIN。"}},400);prune();const subject=browserEvidenceSubjectKey(auth.context);const existing=[...store.values()].find(e=>e.subjectKey===subject&&e.preview.taskId===id&&e.preview.asin===asin);if(existing)return response({ok:true,data:{status:"reused",preview:existing.preview,evidenceId:existing.id}});try{const collectedAt=new Date().toISOString();const browser=await collectBrowserEvidencePreview({asin,capturedAt:collectedAt});if(!browser.extraction.entityBound)return response({ok:false,error:{code:"wrong_asin",message:"Amazon 页面实体与任务绑定 ASIN 不一致，已停止富化。"}},422);const structured=browser.productInfo?.canonicalFacts||{};const preview=await buildAmazonFactEnrichmentPreview({taskId:id,asin,blocks:browser.sellerContent||[],structured,collectedAt,expiresAt:Date.now()+15*60*1000});const evidenceId=randomUUID();store.set(evidenceId,{id:evidenceId,preview,subjectKey:subject});return response({ok:true,data:{status:"collected",preview,evidenceId}});}catch(error){const message=error instanceof Error?error.message:"Amazon 富化采集失败";return response({ok:false,error:{code:"enrichment_unavailable",message:message.includes("验证码")?message:"Amazon 商品补充资料暂时不可用，不影响 Listing 主流程。"}},502);}}
function resetAmazonFactEnrichmentStoreForTests(){store.clear();}

