/**
 * V3 Final Operability Correction — P1-A：Browser-runtime 表达式自包含工件
 *
 * 背景：旧实现用 `fn.toString()` 把模块函数序列化进 Runtime.evaluate 表达式；
 * 生产 SWC minify 会重命名模块标识符（实测 ${z(s)}），序列化后的函数体引用
 * minified 名（s）→ 页面作用域 ReferenceError: s is not defined。
 *
 * 本文件是 browser-runtime extractor 的**显式字符串工件**：
 * - 所有 helper 以固定名显式定义（function 声明）
 * - helper 间引用固定名
 * - 不依赖 Node/module scope、不依赖 bundler rename、不依赖 closure capture
 * - 字符串常量内容不会被 minifier 改写 → MINIFICATION-SAFE
 *
 * 与 detail-page-extract.ts 的 Node 侧工具函数保持行为一致（由
 * detail-page-expression.test.ts 同步校验锁定，防止双份漂移）。
 */

export type AmazonDetailPageExpressionOptions = {
  expectedAsin: string | null;
  capturedAt: string;
  collectorVersion: string;
};

/**
 * 浏览器端源码工件（自包含 IIFE；`__OPTIONS__` 为 options JSON 占位）。
 * 注意：本字符串内的 helper 是 JS 手写版（与 detail-page-extract.ts 的 TS 版
 * 逻辑一致）；改动任一侧必须同步另一侧并更新同步测试。
 */
export const DETAIL_PAGE_EXTRACTOR_SOURCE = [
  "(() => {",
  "function sanitizeDetailText(value, maxLength) {",
  "  if (typeof value !== 'string') return null;",
  "  const normalized = value.replace(/[\\u0000-\\u001F\\u007F]/g, ' ').replace(/\\s+/g, ' ').trim();",
  "  return normalized ? normalized.slice(0, maxLength) : null;",
  "}",
  "function normalizeAsin(value) {",
  "  if (typeof value !== 'string') return null;",
  "  const normalized = value.trim().toUpperCase();",
  "  return /^[A-Z0-9]{10}$/.test(normalized) ? normalized : null;",
  "}",
  "function parseAsinFromDetailUrl(url) {",
  "  try {",
  "    const parsed = new URL(url);",
  "    if (parsed.protocol !== 'https:') return null;",
  "    const hostname = parsed.hostname.toLowerCase();",
  "    if (hostname !== 'www.amazon.com' && hostname !== 'amazon.com') return null;",
  "    const segments = parsed.pathname.split('/').filter(Boolean);",
  "    for (let index = 0; index < segments.length - 1; index += 1) {",
  "      if (segments[index] === 'dp' || segments[index] === 'product') {",
  "        const candidate = normalizeAsin(segments[index + 1]);",
  "        if (candidate) return candidate;",
  "      }",
  "      if (segments[index] === 'aw' && segments[index + 1] === 'd' && segments[index + 2]) {",
  "        const candidate = normalizeAsin(segments[index + 2]);",
  "        if (candidate) return candidate;",
  "      }",
  "    }",
  "  } catch (error) {",
  "    return null;",
  "  }",
  "  return null;",
  "}",
  "function parseDetailPrice(value) {",
  "  const text = typeof value === 'string' ? value.trim() : '';",
  "  if (!/^\\s*(?:US\\$|\\$)/i.test(text)) return null;",
  "  const match = /^\\s*(?:US\\$|\\$)\\s*([0-9]+(?:,[0-9]{3})*(?:\\.[0-9]{1,2})?)\\s*(?:USD)?\\s*$/i.exec(text);",
  "  if (!match) return null;",
  "  const parsed = Number(match[1].replace(/,/g, ''));",
  "  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;",
  "}",
  "function detectDetailPriceCurrency(value) {",
  "  const text = typeof value === 'string' ? value.trim() : '';",
  "  if (/^\\s*(?:US\\$|\\$)/i.test(text)) return 'USD';",
  "  if (/^\\s*(?:JPY|￥|¥)/i.test(text)) return 'JPY';",
  "  if (/^\\s*(?:[A-Z]{3}|€|£)/i.test(text)) return 'other';",
  "  return text ? null : null;",
  "}",
  "function parseDetailRating(value) {",
  "  const text = typeof value === 'string' ? value.trim() : '';",
  "  const match = /^\\s*([0-9]+(?:\\.[0-9]+)?)/.exec(text);",
  "  if (!match) return null;",
  "  const parsed = Number(match[1]);",
  "  return Number.isFinite(parsed) && parsed >= 0 && parsed <= 5 ? parsed : null;",
  "}",
  "function parseDetailReviewCount(value) {",
  "  const text = typeof value === 'string' ? value.trim() : '';",
  "  const match = /^\\s*\\(?\\s*([0-9][0-9,]*)/.exec(text);",
  "  if (!match) return null;",
  "  const parsed = Number(match[1].replace(/,/g, ''));",
  "  return Number.isInteger(parsed) && parsed >= 0 ? parsed : null;",
  "}",
  "function parseDetailBsr(value) {",
  "  const text = typeof value === 'string' ? value.trim() : '';",
  "  const match = /#\\s*([0-9][0-9,]*)/.exec(text);",
  "  if (!match) return null;",
  "  const parsed = Number(match[1].replace(/,/g, ''));",
  "  return Number.isInteger(parsed) && parsed >= 1 ? parsed : null;",
  "}",
  "function detectDetailPageStatus(root) {",
  "  const bodyText = sanitizeDetailText(root.body && root.body.innerText, 4000) || '';",
  "  if (/captcha|robot check|enter the characters you see|type the characters you see|验证码|机器人/i.test(bodyText)) return 'captcha';",
  "  if (/sign in to continue|login to continue|please sign in|登录后继续/i.test(bodyText)) return 'login_wall';",
  "  if (/sorry[, ]+something went wrong|service unavailable|internal server error|页面出错/i.test(bodyText)) return 'error_page';",
  "  return root.querySelector('#productTitle') ? 'ok' : 'unknown_page';",
  "}",
  "function readDetailPageAsinAnchor(root) {",
  "  const containers = ['#detailBullets_feature_div', '#productDetails_detailBullets_sections1', '#prodDetails', '#detailBulletsWrapper_feature_div'];",
  "  for (const containerSelector of containers) {",
  "    const container = root.querySelector(containerSelector);",
  "    if (!container) continue;",
  "    const rows = (container.querySelectorAll && container.querySelectorAll('tr, li')) || [];",
  "    for (const row of rows) {",
  "      const text = sanitizeDetailText(row.textContent, 240) || '';",
  "      const asinMatch = /(?:^|\\s)ASIN\\s*[:：]\\s*([A-Z0-9]{10})(?:\\s|$)/i.exec(text);",
  "      if (asinMatch) return asinMatch[1].toUpperCase();",
  "      const valueOnly = /(?:^|\\s)([A-Z0-9]{10})(?:\\s|$)/.exec(text);",
  "      const label = /ASIN/i.test(text);",
  "      if (label && valueOnly) return valueOnly[1].toUpperCase();",
  "    }",
  "  }",
  "  return null;",
  "}",
  "function readDetailPageBsrText(root) {",
  "  const containers = ['#detailBullets_feature_div', '#productDetails_detailBullets_sections1', '#prodDetails', '#detailBulletsWrapper_feature_div'];",
  "  for (const containerSelector of containers) {",
  "    const container = root.querySelector(containerSelector);",
  "    if (!container) continue;",
  "    const rows = (container.querySelectorAll && container.querySelectorAll('tr, li')) || [];",
  "    for (const row of rows) {",
  "      const text = sanitizeDetailText(row.textContent, 400) || '';",
  "      if (/best sellers rank/i.test(text)) return text;",
  "    }",
  "  }",
  "  return null;",
  "}",
  "function unknownField(field, reason) { return { field, value: null, status: 'unknown', reason }; }",
  "function correctField(field, value) { return { field, value, status: 'correct', reason: null }; }",
  "function readFirstText(root, selectors) {",
  "  for (const selector of selectors) {",
  "    const node = root.querySelector(selector);",
  "    if (node && node.textContent) return node.textContent;",
  "  }",
  "  return null;",
  "}",
  "function extractAmazonDetailPage(root, pageUrl, options) {",
  "  const pageStatus = detectDetailPageStatus(root);",
  "  const urlAsin = parseAsinFromDetailUrl(pageUrl);",
  "  const pageAsin = readDetailPageAsinAnchor(root);",
  "  const expectedAsin = normalizeAsin(options.expectedAsin);",
  "  const productContainerFound = root.querySelector('#productTitle') !== null;",
  "  const urlMatchesExpected = expectedAsin !== null && urlAsin === expectedAsin;",
  "  const pageAnchorMatchesExpected = expectedAsin !== null && pageAsin === expectedAsin;",
  "  const entityBound = pageStatus === 'ok' && productContainerFound && urlMatchesExpected && pageAnchorMatchesExpected;",
  "  const bindingReason = !entityBound",
  "    ? (pageStatus !== 'ok'",
  "      ? 'page_status_' + pageStatus",
  "      : !urlMatchesExpected",
  "        ? 'url_asin_mismatch'",
  "        : !pageAnchorMatchesExpected",
  "          ? 'page_asin_anchor_mismatch'",
  "          : 'product_container_not_found')",
  "    : null;",
  "  const fields = {",
  "    asin: unknownField('asin', 'entity_binding_unproven'),",
  "    title: unknownField('title', 'entity_binding_unproven'),",
  "    price: unknownField('price', 'entity_binding_unproven'),",
  "    bsr: unknownField('bsr', 'entity_binding_unproven'),",
  "    rating: unknownField('rating', 'entity_binding_unproven'),",
  "    reviews: unknownField('reviews', 'entity_binding_unproven'),",
  "  };",
  "  if (entityBound && expectedAsin !== null) {",
  "    const titleNode = root.querySelector('#productTitle');",
  "    const title = sanitizeDetailText(titleNode && titleNode.textContent, 500);",
  "    fields.asin = correctField('asin', expectedAsin);",
  "    fields.title = title ? correctField('title', title) : unknownField('title', 'selector_not_found');",
  "    const priceText = sanitizeDetailText(readFirstText(root, ['#corePriceDisplay_desktop_feature_div .a-price .a-offscreen', '#corePriceDisplay_mobile_feature_div .a-price .a-offscreen', '#corePrice_feature_div .a-offscreen', '#corePrice_feature_div .a-price .a-offscreen', '.priceToPay .a-offscreen', '#priceblock_ourprice', '#priceblock_dealprice']), 60);",
  "    const price = parseDetailPrice(priceText);",
  "    const priceCurrency = detectDetailPriceCurrency(priceText);",
  "    fields.price = price !== null",
  "      ? correctField('price', price)",
  "      : unknownField('price', priceText ? (priceCurrency === 'JPY' || priceCurrency === 'other' ? 'currency_not_usd:' + priceCurrency : 'format_invalid') : 'selector_not_found');",
  "    const bsrText = readDetailPageBsrText(root);",
  "    const bsr = parseDetailBsr(bsrText);",
  "    fields.bsr = bsr !== null ? correctField('bsr', bsr) : unknownField('bsr', bsrText ? 'format_invalid' : 'selector_not_found');",
  "    const ratingText = sanitizeDetailText(root.querySelector('#acrPopover .a-icon-alt') && root.querySelector('#acrPopover .a-icon-alt').textContent, 60);",
  "    const rating = parseDetailRating(ratingText);",
  "    fields.rating = rating !== null ? correctField('rating', rating) : unknownField('rating', ratingText ? 'format_invalid' : 'selector_not_found');",
  "    const reviewsText = sanitizeDetailText(root.querySelector('#acrCustomerReviewText') && root.querySelector('#acrCustomerReviewText').textContent, 60);",
  "    const reviews = parseDetailReviewCount(reviewsText);",
  "    fields.reviews = reviews !== null ? correctField('reviews', reviews) : unknownField('reviews', reviewsText ? 'format_invalid' : 'selector_not_found');",
  "  } else {",
  "    for (const field of Object.keys(fields)) {",
  "      fields[field] = { field, value: null, status: 'unknown', reason: bindingReason || 'entity_binding_unproven' };",
  "    }",
  "  }",
  "  return {",
  "    schemaVersion: 'amazon-detail-page-extraction.v1',",
  "    expectedAsin, urlAsin, pageAsin, entityBound,",
  "    bindingProof: { urlMatchesExpected, pageAnchorMatchesExpected, productContainerFound },",
  "    pageStatus, fields,",
  "    capturedAt: options.capturedAt,",
  "    collectorVersion: options.collectorVersion,",
  "  };",
  "}",
  "return extractAmazonDetailPage(document, location.href, __OPTIONS__);",
  "})()",
].join("\n");

/** 构建 Runtime.evaluate 表达式（self-contained；__OPTIONS__ 占位替换为 options JSON） */
export function buildAmazonDetailPageExtractionExpression(options: AmazonDetailPageExpressionOptions): string {
  return DETAIL_PAGE_EXTRACTOR_SOURCE.replace("__OPTIONS__", JSON.stringify(options));
}

/**
 * V3 Final PHASE 1 — Product Information 提取表达式（浏览器端自包含 IIFE）。
 * 与 detail-page-extract.ts 的 Node 侧（readProductInfoRows / mapProductInfoToCanonical /
 * extractAmazonProductInfo）行为一致；改任一侧必须同步另一侧并更新同步测试。
 * 限定容器（Spike 实证）：#productDetails_expanderTables_depth{Left,Right}Sections 内
 * table.a-keyvalue.prodDetTable + #productOverview_feature_div 内 table；
 * 不触碰 buybox / sponsored / related 区（Related Product Gate）。
 */
export type AmazonProductInfoExpressionOptions = AmazonDetailPageExpressionOptions;

export const PRODUCT_INFO_EXTRACTOR_SOURCE = [
  "(() => {",
  "function sanitizeDetailText(value, maxLength) {",
  "  if (typeof value !== 'string') return null;",
  "  const normalized = value.replace(/[\\u0000-\\u001F\\u007F]/g, ' ').replace(/\\s+/g, ' ').trim();",
  "  return normalized ? normalized.slice(0, maxLength) : null;",
  "}",
  "function normalizeAsin(value) {",
  "  if (typeof value !== 'string') return null;",
  "  const normalized = value.trim().toUpperCase();",
  "  return /^[A-Z0-9]{10}$/.test(normalized) ? normalized : null;",
  "}",
  "function parseAsinFromDetailUrl(url) {",
  "  try {",
  "    const parsed = new URL(url);",
  "    if (parsed.protocol !== 'https:') return null;",
  "    const hostname = parsed.hostname.toLowerCase();",
  "    if (hostname !== 'www.amazon.com' && hostname !== 'amazon.com') return null;",
  "    const segments = parsed.pathname.split('/').filter(Boolean);",
  "    for (let index = 0; index < segments.length - 1; index += 1) {",
  "      if (segments[index] === 'dp' || segments[index] === 'product') {",
  "        const candidate = normalizeAsin(segments[index + 1]);",
  "        if (candidate) return candidate;",
  "      }",
  "    }",
  "  } catch (error) {",
  "    return null;",
  "  }",
  "  return null;",
  "}",
  "function detectDetailPageStatus(root) {",
  "  const bodyText = sanitizeDetailText(root.body && root.body.innerText, 4000) || '';",
  "  if (/captcha|robot check|enter the characters you see|type the characters you see|验证码|机器人/i.test(bodyText)) return 'captcha';",
  "  if (/sign in to continue|login to continue|please sign in|登录后继续/i.test(bodyText)) return 'login_wall';",
  "  if (/sorry[, ]+something went wrong|service unavailable|internal server error|页面出错/i.test(bodyText)) return 'error_page';",
  "  return root.querySelector('#productTitle') ? 'ok' : 'unknown_page';",
  "}",
  "function readDetailPageAsinAnchor(root) {",
  "  const containers = ['#detailBullets_feature_div', '#productDetails_detailBullets_sections1', '#prodDetails', '#detailBulletsWrapper_feature_div'];",
  "  for (const containerSelector of containers) {",
  "    const container = root.querySelector(containerSelector);",
  "    if (!container) continue;",
  "    const rows = (container.querySelectorAll && container.querySelectorAll('tr, li')) || [];",
  "    for (const row of rows) {",
  "      const text = sanitizeDetailText(row.textContent, 240) || '';",
  "      const asinMatch = /(?:^|\\s)ASIN\\s*[:：]\\s*([A-Z0-9]{10})(?:\\s|$)/i.exec(text);",
  "      if (asinMatch) return asinMatch[1].toUpperCase();",
  "      const valueOnly = /(?:^|\\s)([A-Z0-9]{10})(?:\\s|$)/.exec(text);",
  "      const label = /ASIN/i.test(text);",
  "      if (label && valueOnly) return valueOnly[1].toUpperCase();",
  "    }",
  "  }",
  "  return null;",
  "}",
  "const PRODUCT_INFO_CONTAINER_SELECTORS = ['#productDetails_expanderTables_depthLeftSections', '#productDetails_expanderTables_depthRightSections'];",
  "const PRODUCT_INFO_ROW_LIMIT = 60;",
  "const PRODUCT_INFO_TEXT_LIMIT = 200;",
  "function readProductInfoRows(root) {",
  "  const rows = [];",
  "  const seen = {};",
  "  const sections = ['productDetails_depthLeftSections', 'productDetails_depthRightSections'];",
  "  for (let ci = 0; ci < PRODUCT_INFO_CONTAINER_SELECTORS.length; ci += 1) {",
  "    const container = root.querySelector(PRODUCT_INFO_CONTAINER_SELECTORS[ci]);",
  "    if (!container) continue;",
  "    const tableRows = (container.querySelectorAll && container.querySelectorAll('table.a-keyvalue.prodDetTable tr')) || [];",
  "    for (const rowNode of tableRows) {",
  "      const cells = (rowNode.querySelectorAll && rowNode.querySelectorAll('td, th')) || [];",
  "      if (cells.length < 2) continue;",
  "      const label = sanitizeDetailText(cells[0].textContent, PRODUCT_INFO_TEXT_LIMIT);",
  "      const value = sanitizeDetailText(cells[1].textContent, PRODUCT_INFO_TEXT_LIMIT);",
  "      if (!label || !value) continue;",
  "      const key = sections[ci] + ':' + label;",
  "      if (seen[key] || rows.length >= PRODUCT_INFO_ROW_LIMIT) continue;",
  "      seen[key] = true;",
  "      rows.push({ label, value, sourceSection: sections[ci] });",
  "    }",
  "  }",
  "  const overview = root.querySelector('#productOverview_feature_div');",
  "  if (overview) {",
  "    const tableRows = (overview.querySelectorAll && overview.querySelectorAll('table tr')) || [];",
  "    for (const rowNode of tableRows) {",
  "      const cells = (rowNode.querySelectorAll && rowNode.querySelectorAll('td, th')) || [];",
  "      if (cells.length < 2) continue;",
  "      const label = sanitizeDetailText(cells[0].textContent, PRODUCT_INFO_TEXT_LIMIT);",
  "      const value = sanitizeDetailText(cells[1].textContent, PRODUCT_INFO_TEXT_LIMIT);",
  "      if (!label || !value) continue;",
  "      const key = 'productOverview_feature_div:' + label;",
  "      if (seen[key] || rows.length >= PRODUCT_INFO_ROW_LIMIT) continue;",
  "      seen[key] = true;",
  "      rows.push({ label, value, sourceSection: 'productOverview_feature_div' });",
  "    }",
  "  }",
  "  return rows;",
  "}",
  "const PRODUCT_INFO_LABEL_MAP = [",
  "  ['brand', ['Brand Name', 'Brand']],",
  "  ['product_type', ['Item Type Name', 'Bottle Type']],",
  "  ['series_or_model', ['Model Name', 'Model Number']],",
  "  ['material', ['Material Type', 'Material']],",
  "  ['capacity', ['Total Capacity', 'Capacity']],",
  "  ['dimensions', ['Item Dimensions L x W x H', 'Item Dimensions L x W x Thickness', 'Item Dimensions W x H', 'Product Dimensions', 'Size (inches)']],",
  "  ['weight', ['Item Weight']],",
  "  ['color_or_variant', ['Color', 'Theme']],",
  "  ['quantity_or_pack_size', ['Unit Count', 'Number of Items', 'Package Quantity']],",
  "  ['functional_feature', ['Other Special Features of the Product', 'Additional Features', 'Special Feature', 'Material Features', 'Material Feature']],",
  "  ['care', ['Product Care Instructions', 'Care Instructions']],",
  "  ['included_components', ['Included Components']],",
  "  ['operation', ['Lid Type', 'Cap Type', 'Closure Type']],",
  "];",
  "function mapProductInfoToCanonical(rows) {",
  "  const recovered = {};",
  "  const used = {};",
  "  for (const entry of PRODUCT_INFO_LABEL_MAP) {",
  "    const field = entry[0];",
  "    const labels = entry[1];",
  "    for (const label of labels) {",
  "      let found = null;",
  "      for (const row of rows) { if (row.label === label) { found = row; break; } }",
  "      if (found && !used[label]) {",
  "        recovered[field] = found.value;",
  "        used[label] = true;",
  "        break;",
  "      }",
  "    }",
  "  }",
  "  return recovered;",
  "}",
  "function extractAmazonProductInfo(root, pageUrl, options) {",
  "  const pageStatus = detectDetailPageStatus(root);",
  "  const urlAsin = parseAsinFromDetailUrl(pageUrl);",
  "  const pageAsin = readDetailPageAsinAnchor(root);",
  "  const expectedAsin = normalizeAsin(options.expectedAsin);",
  "  const productContainerFound = root.querySelector('#productTitle') !== null;",
  "  const urlMatchesExpected = expectedAsin !== null && urlAsin === expectedAsin;",
  "  const pageAnchorMatchesExpected = expectedAsin !== null && pageAsin === expectedAsin;",
  "  const entityBound = pageStatus === 'ok' && productContainerFound && urlMatchesExpected && pageAnchorMatchesExpected;",
  "  const bindingReason = !entityBound",
  "    ? (pageStatus !== 'ok'",
  "      ? 'page_status_' + pageStatus",
  "      : !urlMatchesExpected",
  "        ? 'url_asin_mismatch'",
  "        : !pageAnchorMatchesExpected",
  "          ? 'page_asin_anchor_mismatch'",
  "          : 'product_container_not_found')",
  "    : null;",
  "  if (!entityBound) {",
  "    return { schemaVersion: 'amazon-product-info-extraction.v1', entityBound, bindingReason, rows: [], canonicalFacts: {}, capturedAt: options.capturedAt, collectorVersion: options.collectorVersion };",
  "  }",
  "  const rows = readProductInfoRows(root);",
  "  return {",
  "    schemaVersion: 'amazon-product-info-extraction.v1',",
  "    entityBound,",
  "    bindingReason,",
  "    rows,",
  "    canonicalFacts: mapProductInfoToCanonical(rows),",
  "    capturedAt: options.capturedAt,",
  "    collectorVersion: options.collectorVersion,",
  "  };",
  "}",
  "return extractAmazonProductInfo(document, location.href, __OPTIONS__);",
  "})()",
].join("\n");

/** 构建 Product Info 提取表达式（self-contained；__OPTIONS__ 占位替换） */
export function buildAmazonProductInfoExtractionExpression(options: AmazonProductInfoExpressionOptions): string {
  return PRODUCT_INFO_EXTRACTOR_SOURCE.replace("__OPTIONS__", JSON.stringify(options));
}
